"""Service de generation et deploiement de profils VPN WireGuard."""

import tempfile
from pathlib import Path

from gui.services.adb_service import ADBResult, ADBService


class VPNService:
    """Genere des profils WireGuard et les deploie via ADB."""

    REMOTE_VPN_DIR = "/sdcard/Download"

    def __init__(self, adb: ADBService) -> None:
        """Initialise le service VPN.

        Args:
            adb: Instance du service ADB pour pousser les configs.
        """
        self.adb = adb

    def generate_wireguard_config(
        self,
        device_name: str,
        private_key: str,
        server_public_key: str,
        server_endpoint: str,
        allowed_ips: str = "10.0.0.0/24",
        dns: str = "10.0.0.1",
        address: str = "",
    ) -> str:
        """Genere un fichier de configuration WireGuard.

        Args:
            device_name: Nom de l'appareil (pour commentaire).
            private_key: Cle privee WireGuard du client.
            server_public_key: Cle publique du serveur WireGuard.
            server_endpoint: Endpoint du serveur (host:port).
            allowed_ips: IPs autorisees a transiter par le VPN.
            dns: Serveur DNS a utiliser.
            address: Adresse IP du client dans le tunnel.

        Returns:
            Contenu du fichier de configuration WireGuard.
        """
        return f"""# WireGuard config for {device_name}
# Generated by Onyx Mobile Manager

[Interface]
PrivateKey = {private_key}
Address = {address}
DNS = {dns}

[Peer]
PublicKey = {server_public_key}
Endpoint = {server_endpoint}
AllowedIPs = {allowed_ips}
PersistentKeepalive = 25
"""

    def push_vpn_config(
        self, serial: str, config_content: str, filename: str = "onyx-vpn.conf"
    ) -> ADBResult:
        """Pousse une configuration VPN sur l'appareil via ADB.

        Args:
            serial: Serial ou IP:port de l'appareil.
            config_content: Contenu de la configuration WireGuard.
            filename: Nom du fichier sur l'appareil.

        Returns:
            Resultat du push ADB.
        """
        with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as tmp:
            tmp.write(config_content)
            tmp_path = tmp.name

        try:
            remote_path = f"{self.REMOTE_VPN_DIR}/{filename}"
            return self.adb.push_file(serial, tmp_path, remote_path)
        finally:
            Path(tmp_path).unlink(missing_ok=True)

    def check_vpn_status(self, serial: str) -> dict[str, str]:
        """Verifie le statut VPN sur l'appareil.

        Args:
            serial: Serial ou IP:port de l'appareil.

        Returns:
            Dict avec 'connected' (bool str) et 'interface' info.
        """
        result = self.adb.shell(serial, "ip addr show wg0")
        if result.success and "wg0" in result.output:
            return {"connected": "true", "interface": result.output}
        return {"connected": "false", "interface": ""}

    def check_onyx_reachability(self, serial: str, target: str = "10.0.0.44") -> bool:
        """Verifie si l'appareil peut joindre le reseau Onyx via VPN.

        Args:
            serial: Serial ou IP:port de l'appareil.
            target: IP a pinger pour tester la connectivite.

        Returns:
            True si le reseau Onyx est joignable.
        """
        result = self.adb.shell(serial, f"ping -c 1 -W 3 {target}")
        return result.success
